version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME_AUTH}
    depends_on:
      - db
    volumes:
      - ./auth:/app

  core:
    build: ./core
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@${DATABASE_HOST}/${DATABASE_NAME_CORE}
    depends_on:
      - db
    volumes:
      - ./core:/app

  gateway:
    build: ./gateway
    ports:
      - "8002:8000"
    depends_on:
      - auth
      - core
    volumes:
      - ./gateway:/app

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

volumes:
  db_data:
