version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: ./auth/Dockerfile
    image: auth_service:1.0.0
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./auth:/app

  core:
    build:
      context: .
      dockerfile: ./core/Dockerfile
    image: core_service:1.0.0
    ports:
      - "8001:8001"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - ./core:/app

  gateway:
    build:
      context: .
      dockerfile: ./gateway/Dockerfile
    image: my_gateway_service:1.0.0
    ports:
      - "8002:8002"
    env_file:
      - .env
    depends_on:
      - auth
      - core
    volumes:
      - ./gateway:/app

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5672:5672"
      - "15672:15672"

  rabbitmq_consumer:
    # Don't need to expose ports since this is only acccessible within docker network
    build: ./rabbitmq_consumer
    image: rabbitmq_consumer_service:latest
    env_file:
      - .env
    depends_on:
      - rabbitmq
    volumes:
      - ./rabbitmq_consumer:/app

volumes:
  db_data: {}
